# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OoX5MGX8Z1Fe7TVgKppKahmFRFpI3uGU
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px

st.set_page_config(
    page_title="Rainfall Prediction",
    page_icon="🌧️",
    layout="wide"
)

# ===========================
# Sidebar
# ===========================

menu = st.sidebar.radio(
    "Menu",
    [
        "🏠 Home",
        "📂 Prediction",
        "📊 Result",
        "📥 Download"
    ]
)

# menyimpan hasil prediksi
if "result" not in st.session_state:
    st.session_state.result = None

# ===================================
# HOME
# ===================================

if menu == "🏠 Home":

    st.title("🌧️ Hybrid TabNet-XGBoost")

    st.subheader("Daily Rainfall Prediction")

    st.write("""
    Aplikasi ini digunakan untuk memprediksi
    intensitas curah hujan harian menggunakan
    model Hybrid TabNet-XGBoost berbasis
    data radiosonde dan meteorologi permukaan.
    """)

    st.info("""
    Alur penggunaan :

    1. Upload Dataset
    2. Klik Predict
    3. Lihat Hasil Prediksi
    4. Download Hasil
    """)

# ===================================
# PREDICTION
# ===================================

elif menu == "📂 Prediction":

    st.title("📂 Rainfall Prediction")

    uploaded = st.file_uploader(
        "Upload Dataset (.xlsx)",
        type=["xlsx"]
    )

    if uploaded:

        df = pd.read_excel(uploaded)

        st.subheader("Preview Dataset")

        st.dataframe(df.head())

        if st.button("🚀 Predict"):

            # ===========================
            # GANTI BAGIAN INI
            # dengan modelmu nanti
            # ===========================

            actual = df["CH"]

            prediction = actual + np.random.normal(0,3,len(df))

            result = pd.DataFrame({

                "Tanggal":df["Tanggal"],
                "Actual":actual,
                "Prediction":prediction

            })

            st.session_state.result = result

            st.success("Prediction Completed!")

# ===================================
# RESULT
# ===================================

elif menu == "📊 Result":

    st.title("📊 Prediction Result")

    if st.session_state.result is None:

        st.warning("Belum ada hasil prediksi.")

    else:

        result = st.session_state.result

        actual = result["Actual"]
        pred = result["Prediction"]

        rmse = np.sqrt(np.mean((actual-pred)**2))
        mae = np.mean(np.abs(actual-pred))

        mask = actual!=0

        mape = np.mean(
            np.abs((actual[mask]-pred[mask])/actual[mask])
        )*100

        c1,c2,c3 = st.columns(3)

        c1.metric("RMSE",round(rmse,2))
        c2.metric("MAE",round(mae,2))
        c3.metric("MAPE (%)",round(mape,2))

        st.divider()

        st.subheader("Actual vs Prediction")

        fig = px.line(
            result,
            x="Tanggal",
            y=["Actual","Prediction"]
        )

        st.plotly_chart(fig,use_container_width=True)

        st.subheader("Prediction Result")

        st.dataframe(result)

# ===================================
# DOWNLOAD
# ===================================

elif menu == "📥 Download":

    st.title("📥 Download Result")

    if st.session_state.result is None:

        st.warning("Belum ada data.")

    else:

        csv = st.session_state.result.to_csv(index=False)

        st.download_button(

            label="⬇ Download Prediction",

            data=csv,

            file_name="prediction.csv",

            mime="text/csv"

        )